name: Continuous Deployment
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ci-check: 
    uses: starswap/DRP24/.github/workflows/ci.yml@main
  cd:
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    container: starswap/dpl:v1
    needs: ci-check
    environment: 
      name: Heroku Production
      url: https://drp24-43a0dc947937.herokuapp.com/
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Deploy to Heroku
      run: "cd frontend && dpl --provider=heroku --app=drp24 --api-key=${{ secrets.HEROKU_API_KEY }}"
