name: Continuous Integration
on:
  workflow_call:
  pull_request:
  workflow_dispatch:

jobs:
  lint: 
    name: Build and Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Build
      run: npm install
    - name: Lint
      run: npm run lint
  test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Build
      run: npm install
    - name: Check compilation
      run: cd frontend && npx tsc && cd ../backend && npx tsc
    - name: Test
      run: npm run test
    - name: Frontend Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()    # run this step even if previous step failed
      with:
        name: Frontend Tests          # Name of the check run which will be created
        path: frontend/reports/*.xml  # Path to test results
        reporter: jest-junit          # Format of test results
    - name: Backend Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()    # run this step even if previous step failed
      with:
        name: Backend Tests         # Name of the check run which will be created
        path: backend/reports/*.xml    # Path to test results
        reporter: jest-junit        # Format of test results